# Generated by Django 6.0.6 on 2026-06-19 05:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Juego',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('precio', models.DecimalField(decimal_places=2, max_digits=10)),
                ('stock', models.PositiveIntegerField(default=0)),
                ('ventas', models.PositiveIntegerField(default=0)),
                ('genero', models.CharField(max_length=50)),
                ('desarrollador', models.CharField(blank=True, max_length=100)),
                ('plataformas', models.CharField(default='PC', max_length=200)),
                ('imagen', models.URLField(blank=True, max_length=500)),
                ('descuento', models.PositiveIntegerField(default=0)),
                ('descripcion', models.TextField()),
            ],
        ),
    ]
