# Generated by Django 6.0.6 on 2026-06-19 05:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('APP', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='juego',
            name='video_url',
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
    ]
